name: Lint

on:
    push:
        branches:
            - 'dev'
    pull_request:

jobs:
    lint-front:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: '24'

            - name: Install front dependencies
              run: |
                  corepack enable
                  corepack use pnpm@latest
                  pnpm i

            - name: Run frontend lint
              run: pnpm lint:front

    lint-backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                  go-version-file: 'go.work'

            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@v9
              with:
                  skip-cache: true
                  working-directory: backend

    lint-worker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                  go-version-file: 'go.work'

            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@v9
              with:
                  version: latest
                  working-directory: worker
